#! /bin/sh
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II
bspc monitor DP-0 -d III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# xprop WM_CLASS

bspc rule -a discord desktop=^2 state=tiled
bspc rule -a Google-chrome-beta desktop=^3 state=tiled
bspc rule -a Streamdeck UI desktop=^0 state=tiled
bspc rule -a ROX-Filer state=tiled
bspc rule -a resolve desktop=^8 state=floating
